/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/audit/{entity_type}/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Audit Trail
         * @description Return the full audit trail for an entity, newest first.
         *
         *     Each entry records who did what and when, with a payload that captures the
         *     before/after state. This is the structural answer to "how did this value get
         *     here?" — the question every compliance review asks.
         */
        get: operations["get_audit_trail_audit__entity_type___entity_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange credentials for a session
         * @description Authenticate and issue a session cookie.
         *
         *     Every failure is the same 401 with the same message. Distinguishing "no
         *     such user" from "wrong password" would turn this endpoint into a directory
         *     of who works here.
         *
         *     Too many recent failures answer 429 with `Retry-After` instead. That is
         *     visible to an attacker by construction -- a rate limit that could not be
         *     observed could not be obeyed either -- but it says nothing about whether
         *     the username exists, because failed attempts are counted for usernames that
         *     do not.
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke this session
         * @description Revoke the session and clear the cookie.
         *
         *     Deliberately 204 whether or not a live session was found. Logging out is
         *     idempotent, and reporting "you were not logged in" tells an unauthenticated
         *     caller something about a token they hold.
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The authenticated user */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clauses/{clause_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A clause with its chunk text and the quote's offsets within it
         * @description The provenance endpoint — what turns a citation into something checkable.
         *
         *     `quote_start`/`quote_end` locate the quote inside `chunk_text`. They are
         *     null when the quote could not be located, and a client must then render the
         *     quote without highlighting rather than falling back to an approximate span.
         */
        get: operations["get_clause_clauses__clause_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List documents */
        get: operations["list_documents_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload a PDF for ingestion
         * @description Store the PDF and queue it for parsing.
         *
         *     Returns 201 for a new document and 200 when the bytes were already known --
         *     a duplicate is a correct outcome, not an error (CLAUDE.md 1.7).
         */
        post: operations["upload_document_documents_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one document */
        get: operations["get_document_documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/chunks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chunks with their character spans */
        get: operations["list_chunks_documents__document_id__chunks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/covenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Covenants extracted from a document */
        get: operations["list_document_covenants_documents__document_id__covenants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Per-page parse telemetry */
        get: operations["list_pages_documents__document_id__pages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse and chunk now, without waiting for the worker
         * @description Run ingestion inline.
         *
         *     The worker picks queued documents up on its own; this exists for operators
         *     and demos that do not want to wait for a poll interval.
         */
        post: operations["process_document_documents__document_id__process_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Where a document has got to in the pipeline
         * @description Progress for a client that is watching an upload.
         *
         *     The worker has always recorded this -- `extraction_jobs` is the queue, and
         *     it carries the status, the timings and the failure message -- but nothing
         *     exposed it over HTTP, so the only way to know whether an upload had been
         *     ingested was to look in the database (docs/review.md, finding 7).
         */
        get: operations["document_status_documents__document_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instruments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List instruments */
        get: operations["list_instruments_instruments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instruments/{instrument_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One instrument with its covenants, calls and rating triggers */
        get: operations["get_instrument_instruments__instrument_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instruments/{instrument_id}/covenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Covenants for an instrument, each with its source clause */
        get: operations["list_instrument_covenants_instruments__instrument_id__covenants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List portfolios */
        get: operations["list_portfolios_portfolios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/{portfolio_id}/holdings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Positions and exposure for a portfolio
         * @description Holdings for a date, defaulting to the most recent available.
         *
         *     The response echoes `as_of_date`, because holdings are a time series and a
         *     caller that does not know which date it received cannot report the exposure
         *     responsibly.
         */
        get: operations["get_portfolio_holdings_portfolios__portfolio_id__holdings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask the query agent
         * @description Answer a question with citations, or refuse.
         *
         *     The agent logs every question to `query_logs` regardless of outcome, so a
         *     refusal is as auditable as an answer.
         */
        post: operations["ask_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Pending
         * @description List items awaiting human review.
         */
        get: operations["list_pending_review_pending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review/{review_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Review
         * @description Accept the machine-extracted value.
         *
         *     The old_value stays as-is; the review is marked APPROVED. An audit log
         *     entry records who approved it and when.
         */
        post: operations["approve_review_review__review_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review/{review_id}/correct": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Correct Review
         * @description Replace the machine-extracted value with a human-corrected one.
         *
         *     The original `old_value` is preserved so the audit trail can reconstruct
         *     what the machine said. `new_value` records the human correction. An audit
         *     log entry captures all three states (old, new, corrected).
         */
        post: operations["correct_review_review__review_id__correct_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review/{review_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject Review
         * @description Reject a review item (false positive, not applicable, etc.).
         *
         *     The original value is preserved in the audit trail. A reason is required
         *     so the rejection can be audited and the extractor can be improved.
         */
        post: operations["reject_review_review__review_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApproveRequest */
        ApproveRequest: {
            /** Notes */
            notes?: string | null;
        };
        /**
         * AuditEntry
         * @description One row from the audit log.
         */
        AuditEntry: {
            /** Action */
            action: string;
            /** Actor Id */
            actor_id?: string | null;
            /** Actor Type */
            actor_type: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Entity Id */
            entity_id?: string | null;
            /** Entity Type */
            entity_type?: string | null;
            /** Id */
            id: string;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            } | null;
            /** Request Id */
            request_id?: string | null;
        };
        /** AuditTrailResponse */
        AuditTrailResponse: {
            /** Count */
            count: number;
            /** Entity Id */
            entity_id: string;
            /** Entity Type */
            entity_type: string;
            /** Entries */
            entries: components["schemas"]["AuditEntry"][];
        };
        /** Body_upload_document_documents_upload_post */
        Body_upload_document_documents_upload_post: {
            /** @default unknown */
            document_type: components["schemas"]["DocumentType"];
            /**
             * File
             * @description PDF to ingest
             */
            file: string;
            /** @default upload */
            source_type: components["schemas"]["SourceType"];
            /** Uploaded By */
            uploaded_by?: string | null;
        };
        /** CallScheduleRead */
        CallScheduleRead: {
            /**
             * Call Date
             * Format: date
             */
            call_date: string;
            /** Call Price */
            call_price?: string | null;
            call_type: components["schemas"]["CallType"];
            /** Confidence */
            confidence?: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            method: components["schemas"]["ExtractionMethod"];
            review_status: components["schemas"]["ReviewStatus"];
            /** Source Clause Id */
            source_clause_id?: string | null;
        };
        /**
         * CallType
         * @enum {string}
         */
        CallType: "optional" | "mandatory" | "make_whole" | "clean_up" | "tax" | "regulatory";
        /**
         * ChunkType
         * @enum {string}
         */
        ChunkType: "paragraph" | "table" | "heading" | "list" | "footnote" | "unknown";
        /**
         * Citation
         * @description A pointer back to the text a claim came from (CLAUDE.md 1.2).
         */
        Citation: {
            /** Char End */
            char_end?: number | null;
            /** Char Start */
            char_start?: number | null;
            /** Chunk Id */
            chunk_id?: string | null;
            /** Clause Id */
            clause_id?: string | null;
            /** Document Id */
            document_id: string;
            /** Page Number */
            page_number: number;
            /** Quote */
            quote: string;
            /** Section Title */
            section_title?: string | null;
        };
        /**
         * ClauseProvenance
         * @description A clause plus the chunk text it was cut from.
         *
         *     This is what makes the citation chain inspectable rather than merely
         *     recorded: `chunk_text` is the surrounding context, and
         *     `quote_start` / `quote_end` locate the quote *within that text* so a viewer
         *     can highlight it without re-deriving offsets.
         *
         *     The offsets on `Clause` are relative to the document, not to the chunk, so
         *     they cannot be used for that directly -- these are resolved by the service.
         */
        ClauseProvenance: {
            /** Chunk Text */
            chunk_text?: string | null;
            /** Clause Text */
            clause_text: string;
            /** Confidence */
            confidence?: number | null;
            /** Covenants */
            covenants?: components["schemas"]["CovenantRead"][];
            /** Document Filename */
            document_filename?: string | null;
            method: components["schemas"]["ExtractionMethod"];
            /** Quote End */
            quote_end?: number | null;
            /** Quote Start */
            quote_start?: number | null;
            review_status: components["schemas"]["ReviewStatus"];
            source: components["schemas"]["ClauseSource"];
        };
        /**
         * ClauseSource
         * @description Where a structured fact came from, in enough detail to go look.
         *
         *     `char_start` / `char_end` are what let a viewer highlight the exact span
         *     inside the chunk rather than merely naming the page.
         */
        ClauseSource: {
            /** Char End */
            char_end?: number | null;
            /** Char Start */
            char_start?: number | null;
            /** Chunk Id */
            chunk_id?: string | null;
            /** Citation Match Score */
            citation_match_score?: number | null;
            /** Citation Verified */
            citation_verified: boolean;
            /**
             * Clause Id
             * Format: uuid
             */
            clause_id: string;
            clause_type: components["schemas"]["ClauseType"];
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Page Number */
            page_number: number;
            /** Section Title */
            section_title?: string | null;
            /** Source Quote */
            source_quote: string;
        };
        /**
         * ClauseType
         * @enum {string}
         */
        ClauseType: "negative_pledge" | "cross_default" | "change_of_control" | "financial_covenant" | "rating_trigger" | "call_option" | "put_option" | "profit_step_up" | "dissolution_event" | "purchase_undertaking" | "shariah_compliance" | "event_of_default" | "covenant_other";
        /** CorrectRequest */
        CorrectRequest: {
            /** New Value */
            new_value: string;
            /** Notes */
            notes?: string | null;
        };
        /** CovenantRead */
        CovenantRead: {
            /** Conditions */
            conditions?: {
                [key: string]: unknown;
            };
            /** Confidence */
            confidence?: number | null;
            covenant_type: components["schemas"]["CovenantType"];
            /** Effective Date */
            effective_date?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Instrument Id */
            instrument_id?: string | null;
            method: components["schemas"]["ExtractionMethod"];
            review_status: components["schemas"]["ReviewStatus"];
            severity: components["schemas"]["Severity"];
            source: components["schemas"]["ClauseSource"];
            /** Summary */
            summary?: string | null;
            /** Threshold Amount */
            threshold_amount?: string | null;
            /** Threshold Currency */
            threshold_currency?: string | null;
            /** Thresholds */
            thresholds?: {
                [key: string]: unknown;
            };
            /** Trigger Event */
            trigger_event?: string | null;
        };
        /**
         * CovenantType
         * @enum {string}
         */
        CovenantType: "negative_pledge" | "cross_default" | "change_of_control" | "gearing_ratio" | "interest_cover" | "finance_service_cover" | "minimum_net_worth" | "rating_trigger" | "disposal_restriction" | "distribution_restriction" | "shariah_non_compliance" | "other";
        /** DocumentChunkRead */
        DocumentChunkRead: {
            /** Char End */
            char_end: number;
            /** Char Start */
            char_start: number;
            /** Chunk Text */
            chunk_text: string;
            chunk_type: components["schemas"]["ChunkType"];
            /** Fts Config */
            fts_config: string;
            /** Hash */
            hash: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            language: components["schemas"]["Language"];
            /** Ordinal */
            ordinal: number;
            /** Page Number */
            page_number: number;
            /** Section Title */
            section_title: string | null;
        };
        /** DocumentPageRead */
        DocumentPageRead: {
            /** Char Count */
            char_count: number;
            /** Confidence */
            confidence: number;
            /** Garbled Unicode Ratio */
            garbled_unicode_ratio: number;
            /** Has Text Layer */
            has_text_layer: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Image Area Ratio */
            image_area_ratio: number;
            /** Page Number */
            page_number: number;
            parse_method: components["schemas"]["ParseMethod"];
            /** Vlm Reason */
            vlm_reason: string | null;
            /** Vlm Used */
            vlm_used: boolean;
        };
        /** DocumentRead */
        DocumentRead: {
            /** Byte Size */
            byte_size: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            document_type: components["schemas"]["DocumentType"];
            /** Filename */
            filename: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Issuer Name Guess */
            issuer_name_guess: string | null;
            language: components["schemas"]["Language"];
            /** Page Count */
            page_count: number | null;
            /** Parse Confidence */
            parse_confidence: number | null;
            /** Sha256 */
            sha256: string;
            source_type: components["schemas"]["SourceType"];
            status: components["schemas"]["DocumentStatus"];
            /** Storage Uri */
            storage_uri: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Uploaded By */
            uploaded_by: string | null;
        };
        /**
         * DocumentStatus
         * @enum {string}
         */
        DocumentStatus: "uploaded" | "parsing" | "parsed" | "chunked" | "embedded" | "extracting" | "extracted" | "failed" | "budget_exceeded";
        /**
         * DocumentStatusRead
         * @description Where a document has got to, for a client that is watching it.
         *
         *     Assembled rather than reflected: `documents.status` alone cannot say
         *     whether the worker has picked the document up, and `extraction_jobs` alone
         *     cannot say how many pages came out. Both are needed to answer "is it done,
         *     and did it work?", which is the only question this endpoint exists for.
         */
        DocumentStatusRead: {
            /** Chunk Count */
            chunk_count: number;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Error */
            error?: string | null;
            /** Filename */
            filename: string;
            /** Jobs */
            jobs: components["schemas"]["IngestionJobRead"][];
            /** Page Count */
            page_count: number | null;
            /** Pages Flagged For Vlm */
            pages_flagged_for_vlm: number;
            /** Parse Confidence */
            parse_confidence: number | null;
            status: components["schemas"]["DocumentStatus"];
            /** Terminal */
            terminal: boolean;
        };
        /**
         * DocumentType
         * @enum {string}
         */
        DocumentType: "prospectus" | "information_memorandum" | "trust_deed" | "rating_report" | "announcement" | "supplemental" | "unknown";
        /**
         * ExtractionMethod
         * @description How a value was obtained. PLAN.md 3 -- rule and llm run in parallel.
         * @enum {string}
         */
        ExtractionMethod: "rule" | "llm" | "vlm" | "human";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Environment */
            environment: string;
            /** Service */
            service: string;
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /**
         * HoldingRead
         * @description A position, with the instrument resolved.
         *
         *     `market_value` and `nav_weight` stay `Decimal` to the wire, where Pydantic
         *     renders them as JSON **strings**. That is what keeps CLAUDE.md 6 true past
         *     the boundary: a numeric literal would be parsed into a double by any
         *     browser, undoing the exactness Postgres and Python maintained. Clients must
         *     parse these with a decimal type, not `Number()`.
         */
        HoldingRead: {
            /**
             * As Of Date
             * Format: date
             */
            as_of_date: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            instrument: components["schemas"]["InstrumentRead"];
            /** Market Value */
            market_value?: string | null;
            /** Nav Weight */
            nav_weight?: string | null;
            /** Quantity */
            quantity?: string | null;
            /** Source */
            source?: string | null;
        };
        /**
         * IngestionJobRead
         * @description One row of `extraction_jobs`, as the upload screen needs to read it.
         *
         *     The failure message is included deliberately. A document that stops at
         *     "failed" with no reason on screen sends the operator to the container logs,
         *     and the reason is usually one sentence the service already wrote down.
         */
        IngestionJobRead: {
            /** Error Message */
            error_message: string | null;
            /** Finished At */
            finished_at: string | null;
            job_type: components["schemas"]["JobType"];
            /** Started At */
            started_at: string | null;
            status: components["schemas"]["JobStatus"];
        };
        /** IngestionResponse */
        IngestionResponse: {
            /** Chunk Count */
            chunk_count: number;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Page Count */
            page_count: number;
            /** Pages Flagged For Vlm */
            pages_flagged_for_vlm: number;
            /** Skipped */
            skipped: boolean;
            status: components["schemas"]["DocumentStatus"];
        };
        /**
         * InstrumentDetail
         * @description An instrument with everything that hangs off it.
         *
         *     Assembled in one response because the screens that need an instrument need
         *     its covenants, calls and triggers together; four round trips to render one
         *     page is a worse contract than one slightly larger payload.
         */
        InstrumentDetail: {
            /** Call Schedules */
            call_schedules?: components["schemas"]["CallScheduleRead"][];
            /** Covenants */
            covenants?: components["schemas"]["CovenantRead"][];
            /** Currency */
            currency: string;
            /** Current Rating */
            current_rating?: string | null;
            /** Current Rating Rank */
            current_rating_rank?: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Instrument Name */
            instrument_name: string;
            instrument_type: components["schemas"]["InstrumentType"];
            /** Isin */
            isin?: string | null;
            /** Issue Size */
            issue_size?: string | null;
            /** Issuer Name */
            issuer_name: string;
            /** Maturity Date */
            maturity_date?: string | null;
            rating_agency: components["schemas"]["RatingAgency"];
            /** Rating Triggers */
            rating_triggers?: components["schemas"]["RatingTriggerRead"][];
            review_status: components["schemas"]["ReviewStatus"];
            sukuk_structure: components["schemas"]["SukukStructureType"];
            sukuk_structure_detail?: components["schemas"]["SukukStructureRead"] | null;
            /** Ticker */
            ticker?: string | null;
        };
        /** InstrumentRead */
        InstrumentRead: {
            /** Currency */
            currency: string;
            /** Current Rating */
            current_rating?: string | null;
            /** Current Rating Rank */
            current_rating_rank?: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Instrument Name */
            instrument_name: string;
            instrument_type: components["schemas"]["InstrumentType"];
            /** Isin */
            isin?: string | null;
            /** Issue Size */
            issue_size?: string | null;
            /** Issuer Name */
            issuer_name: string;
            /** Maturity Date */
            maturity_date?: string | null;
            rating_agency: components["schemas"]["RatingAgency"];
            review_status: components["schemas"]["ReviewStatus"];
            sukuk_structure: components["schemas"]["SukukStructureType"];
            /** Ticker */
            ticker?: string | null;
        };
        /**
         * InstrumentType
         * @enum {string}
         */
        InstrumentType: "sukuk" | "conventional_bond" | "mtn" | "perpetual" | "unknown";
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "succeeded" | "failed" | "budget_exceeded" | "cancelled";
        /**
         * JobType
         * @enum {string}
         */
        JobType: "parse" | "chunk" | "embed" | "classify" | "extract_covenant" | "extract_sukuk_structure" | "extract_call_schedule" | "extract_rating_trigger" | "validate";
        /**
         * Language
         * @enum {string}
         */
        Language: "en" | "ms" | "mixed" | "unknown";
        /** LoginRequest */
        LoginRequest: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            user: components["schemas"]["UserRead"];
        };
        /**
         * ParseMethod
         * @enum {string}
         */
        ParseMethod: "pymupdf" | "pdfplumber" | "vlm" | "none";
        /** PendingResponse */
        PendingResponse: {
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["ReviewItem"][];
            /** Total Pending */
            total_pending: number;
        };
        /**
         * PortfolioHoldings
         * @description Holdings for one portfolio on one date.
         *
         *     `as_of_date` is echoed because holdings are a time series and the default
         *     is "latest available" -- a caller that does not know which date it got
         *     cannot report the number responsibly.
         */
        PortfolioHoldings: {
            /** As Of Date */
            as_of_date?: string | null;
            /** Count */
            count: number;
            /** Holdings */
            holdings?: components["schemas"]["HoldingRead"][];
            portfolio: components["schemas"]["PortfolioRead"];
            /** Total Market Value */
            total_market_value?: string | null;
        };
        /** PortfolioRead */
        PortfolioRead: {
            /** Base Currency */
            base_currency: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Mandate Type */
            mandate_type?: string | null;
            /** Name */
            name: string;
            /** Owner */
            owner?: string | null;
        };
        /**
         * QueryIntent
         * @description PLAN.md 5 -- the LangGraph classifier's output space.
         * @enum {string}
         */
        QueryIntent: "document_search" | "covenant_lookup" | "instrument_lookup" | "portfolio_query" | "covenant_breach_check" | "unsupported";
        /**
         * QueryRequest
         * @description Just the question.
         *
         *     `user_id` used to be a field here. It is now taken from the session, for
         *     the same reason `reviewer_id` was removed from the review queue: a
         *     `query_logs` row that records whoever the caller claimed to be is not an
         *     audit trail, it is a suggestion.
         */
        QueryRequest: {
            /** Question */
            question: string;
        };
        /**
         * QueryResponse
         * @description What the agent concluded, and everything needed to audit the conclusion.
         *
         *     `citations` carries the provenance for claims drawn from document text; the
         *     graph's verify node has already stripped any that did not trace to a chunk
         *     retrieved this turn (CLAUDE.md 1.2).
         *
         *     It is legitimately **empty** for intents answered from structured rows
         *     rather than prose -- `covenant_breach_check` and `portfolio_query` report
         *     what the rules engine computed over `covenants` and `portfolio_holdings`,
         *     and cite no span because they read none. Those rows trace to clauses of
         *     their own, so the provenance exists; this response just does not carry it
         *     yet. A UI should link through the instrument rather than assume a citation.
         */
        QueryResponse: {
            /** Answer */
            answer: string;
            /** Chunk Ids */
            chunk_ids: string[];
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /** Confidence */
            confidence: number;
            intent: components["schemas"]["QueryIntent"];
            /** Question */
            question: string;
            /** Refused */
            refused: boolean;
            /** Request Id */
            request_id?: string | null;
            /** Tools Used */
            tools_used: string[];
        };
        /**
         * RatingAgency
         * @enum {string}
         */
        RatingAgency: "MARC" | "RAM" | "SP" | "MOODYS" | "FITCH" | "unknown";
        /** RatingTriggerRead */
        RatingTriggerRead: {
            /** Confidence */
            confidence?: number | null;
            /** Consequence */
            consequence: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            method: components["schemas"]["ExtractionMethod"];
            rating_agency: components["schemas"]["RatingAgency"];
            review_status: components["schemas"]["ReviewStatus"];
            severity: components["schemas"]["Severity"];
            /** Source Clause Id */
            source_clause_id?: string | null;
            trigger_direction: components["schemas"]["TriggerDirection"];
            /** Trigger Rank */
            trigger_rank: number;
            /** Trigger Rating */
            trigger_rating: string;
        };
        /** ReadyResponse */
        ReadyResponse: {
            /** Checks */
            checks: {
                [key: string]: boolean;
            };
            /** Status */
            status: string;
        };
        /** RejectRequest */
        RejectRequest: {
            /** Notes */
            notes?: string | null;
            /** Reason */
            reason: string;
        };
        /** ReviewActionResponse */
        ReviewActionResponse: {
            /** Action */
            action: string;
            /** Entity Id */
            entity_id: string;
            /** Entity Type */
            entity_type: string;
            /** Field Name */
            field_name: string;
            /** Id */
            id: string;
            /** Status */
            status: string;
        };
        /**
         * ReviewItem
         * @description One item in the review queue.
         */
        ReviewItem: {
            /** Confidence */
            confidence?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Entity Id */
            entity_id: string;
            /** Entity Type */
            entity_type: string;
            /** Field Name */
            field_name: string;
            /** Id */
            id: string;
            /** New Value */
            new_value?: string | null;
            /** Old Value */
            old_value?: string | null;
            /** Page Number */
            page_number?: number | null;
            /** Review Notes */
            review_notes?: string | null;
            /** Reviewed At */
            reviewed_at?: string | null;
            /** Reviewer Id */
            reviewer_id?: string | null;
            /** Source Quote */
            source_quote?: string | null;
            /** Status */
            status: string;
            /** Trigger Reason */
            trigger_reason: string;
        };
        /**
         * ReviewStatus
         * @enum {string}
         */
        ReviewStatus: "not_required" | "pending" | "approved" | "rejected" | "corrected";
        /**
         * Severity
         * @enum {string}
         */
        Severity: "informational" | "low" | "medium" | "high" | "critical";
        /**
         * SourceType
         * @enum {string}
         */
        SourceType: "upload" | "email" | "bursa" | "rating_agency" | "internal";
        /** SukukStructureRead */
        SukukStructureRead: {
            /** Confidence */
            confidence?: number | null;
            /** Dissolution Events */
            dissolution_events?: {
                [key: string]: unknown;
            }[];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Originator */
            originator?: string | null;
            /** Profit Payment Frequency */
            profit_payment_frequency?: string | null;
            /** Profit Rate */
            profit_rate?: string | null;
            /** Purchase Undertaking */
            purchase_undertaking?: boolean | null;
            review_status: components["schemas"]["ReviewStatus"];
            /** Shariah Compliance Events */
            shariah_compliance_events?: {
                [key: string]: unknown;
            }[];
            /** Spv Name */
            spv_name?: string | null;
            structure_type: components["schemas"]["SukukStructureType"];
            /** Underlying Asset */
            underlying_asset?: string | null;
        };
        /**
         * SukukStructureType
         * @description Shariah contract underlying the issuance.
         * @enum {string}
         */
        SukukStructureType: "ijarah" | "wakalah" | "musharakah" | "mudharabah" | "murabahah" | "istisna" | "hybrid" | "unknown";
        /**
         * TriggerDirection
         * @enum {string}
         */
        TriggerDirection: "downgrade_below" | "upgrade_above" | "withdrawal" | "any_change";
        /**
         * UploadResponse
         * @description Upload outcome.
         *
         *     `duplicate` is a normal result, not an error: the same bytes uploaded twice
         *     are one document (CLAUDE.md 1.7), and the caller gets the existing row back.
         */
        UploadResponse: {
            document: components["schemas"]["DocumentRead"];
            /** Duplicate */
            duplicate: boolean;
        };
        /**
         * UserRead
         * @description A user, minus everything that would be unwise to serve.
         *
         *     No `password_hash`, and no way to add one by accident: the fields are
         *     listed rather than inherited from the ORM row.
         */
        UserRead: {
            /** Display Name */
            display_name: string;
            /** Email */
            email?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Last Login At */
            last_login_at?: string | null;
            role: components["schemas"]["UserRole"];
            /** Username */
            username: string;
        };
        /**
         * UserRole
         * @description Who may do what.
         *
         *     Two roles, not a permission matrix. The only privileged action in the
         *     system is deciding a review-queue item -- that is the point at which a
         *     human overrides the machine and the audit trail records their name, so it
         *     is the one thing worth gating. Everything else is reading.
         *
         *     Deliberately not OIDC groups or an RBAC table (CLAUDE.md 9 defers those).
         * @enum {string}
         */
        UserRole: "analyst" | "reviewer";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_audit_trail_audit__entity_type___entity_id__get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                entity_type: string;
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditTrailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    get_clause_clauses__clause_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clause_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClauseProvenance"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_documents_get: {
        parameters: {
            query?: {
                status_filter?: components["schemas"]["DocumentStatus"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_document_documents_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_documents_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_chunks_documents__document_id__chunks_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentChunkRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_document_covenants_documents__document_id__covenants_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CovenantRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pages_documents__document_id__pages_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentPageRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    process_document_documents__document_id__process_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    document_status_documents__document_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentStatusRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_instruments_instruments_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_instrument_instruments__instrument_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instrument_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_instrument_covenants_instruments__instrument_id__covenants_get: {
        parameters: {
            query?: {
                covenant_type?: components["schemas"]["CovenantType"] | null;
            };
            header?: never;
            path: {
                instrument_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CovenantRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_portfolios_portfolios_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_portfolio_holdings_portfolios__portfolio_id__holdings_get: {
        parameters: {
            query?: {
                as_of?: string | null;
            };
            header?: never;
            path: {
                portfolio_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioHoldings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
        };
    };
    list_pending_review_pending_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_review_review__review_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    correct_review_review__review_id__correct_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorrectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_review_review__review_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
