"""login attempts

Revision ID: 70d74076b335
Revises: df62ce038a72
Create Date: 2026-08-10 07:47:08.197770+00:00

The rate limiter's counter (app/auth/rate_limit.py). One row per credential
check: who was tried, from where, and whether it worked.

The revoke at the end is not optional bookkeeping. `docker/postgres/init` sets
`ALTER DEFAULT PRIVILEGES`, so a table created here arrives readable by
`opuscovintel_ro` -- and this one is a list of usernames and the addresses they
were tried from, which is neither needed to answer a covenant question nor
something the query agent should be able to read.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70d74076b335'
down_revision: Union[str, Sequence[str], None] = 'df62ce038a72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

READONLY_ROLE = "opuscovintel_ro"
TABLE = "login_attempts"


def revoke_sql(*, role: str = READONLY_ROLE) -> str:
    """Keep the new table out of the query agent's reach.

    Guarded on the role existing: the test database is built with
    `Base.metadata.create_all` and CI has no read-only role, and a migration
    that failed there would fail for a reason unrelated to the schema.

    Exposed as a function so a test can run the statement this migration runs,
    rather than a retyped copy of it.
    """
    return f"""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '{role}') THEN
                REVOKE ALL ON TABLE {TABLE} FROM {role};
            END IF;
        END
        $$;
    """


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(username) > 0', name=op.f('ck_login_attempts_username_not_empty')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_attempts'))
    )
    op.create_index('ix_login_attempts_client_ip_created_at', 'login_attempts', ['client_ip', 'created_at'], unique=False)
    op.create_index('ix_login_attempts_username_created_at', 'login_attempts', ['username', 'created_at'], unique=False)
    # ### end Alembic commands ###

    op.execute(revoke_sql())


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_login_attempts_username_created_at', table_name='login_attempts')
    op.drop_index('ix_login_attempts_client_ip_created_at', table_name='login_attempts')
    op.drop_table('login_attempts')
    # ### end Alembic commands ###
