"""users and sessions

Revision ID: 1be910495383
Revises: 4c1f2a7be913
Create Date: 2026-08-07 06:52:45.418147+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1be910495383'
down_revision: Union[str, Sequence[str], None] = '4c1f2a7be913'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('role', sa.Enum('analyst', 'reviewer', name='ck_userrole', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("password_hash LIKE 'scrypt$%'", name=op.f('ck_users_password_hash_is_encoded')),
    sa.CheckConstraint('length(password_hash) > 0', name=op.f('ck_users_password_hash_not_empty')),
    sa.CheckConstraint('length(username) > 0', name=op.f('ck_users_username_not_empty')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('user_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(token_fingerprint) = 64', name=op.f('ck_user_sessions_fingerprint_is_sha256_hex')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions')),
    sa.UniqueConstraint('token_fingerprint', name=op.f('uq_user_sessions_token_fingerprint'))
    )
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_index('ix_user_sessions_user_id_expires_at', 'user_sessions', ['user_id', 'expires_at'], unique=False)
    # ### end Alembic commands ###

    _revoke_from_readonly_role()


def _revoke_from_readonly_role() -> None:
    """Keep credentials out of reach of the query agent's role.

    `docker/postgres/init` sets ALTER DEFAULT PRIVILEGES so `opuscovintel_ro`
    gets SELECT on every table Alembic creates from Phase 2 onward. That was
    right for the covenant tables and is wrong for these two: it would hand the
    agent's role read access to password hashes and live session fingerprints.

    The SQL guardrail's allowlist already excludes both tables, but that init
    script calls the grant "the actual boundary" and the guardrail "defence in
    depth" -- so the boundary is what needs moving.

    Guarded on the role existing: the test database is built with
    `Base.metadata.create_all` and CI has no read-only role, and a migration
    that fails there would fail for a reason unrelated to the schema.
    """
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'opuscovintel_ro') THEN
                REVOKE ALL ON TABLE users, user_sessions FROM opuscovintel_ro;
            END IF;
        END
        $$;
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_sessions_user_id_expires_at', table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
