"""initial schema

Revision ID: 950444bd060a
Revises: 
Create Date: 2026-08-04 08:03:01.929240+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '950444bd060a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Extensions first. docker/postgres-init.sql also creates these, but
    # that script only runs on first initialisation of a local volume -- against
    # a managed Postgres (RDS, Cloud SQL) the migration is the only thing that
    # runs, and document_chunks.embedding cannot be created without `vector`.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_type', sa.Enum('user', 'system', 'agent', name='ck_actortype', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_type'), 'audit_logs', ['actor_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index('ix_audit_logs_entity_type_entity_id', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_table('documents',
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('storage_uri', sa.String(length=1024), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.Enum('upload', 'email', 'bursa', 'rating_agency', 'internal', name='ck_sourcetype', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('document_type', sa.Enum('prospectus', 'information_memorandum', 'trust_deed', 'rating_report', 'announcement', 'supplemental', 'unknown', name='ck_documenttype', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'parsing', 'parsed', 'chunked', 'embedded', 'extracting', 'extracted', 'failed', 'budget_exceeded', name='ck_documentstatus', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('language', sa.Enum('en', 'ms', 'mixed', 'unknown', name='ck_language', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('issuer_name_guess', sa.String(length=512), nullable=True),
    sa.Column('instrument_name_guess', sa.String(length=512), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('parse_confidence', sa.Float(), nullable=True),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('page_count IS NULL OR page_count >= 0', name=op.f('ck_documents_page_count_non_negative')),
    sa.CheckConstraint('parse_confidence IS NULL OR (parse_confidence >= 0 AND parse_confidence <= 1)', name=op.f('ck_documents_parse_confidence_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('sha256', name=op.f('uq_documents_sha256'))
    )
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_table('human_reviews',
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.String(length=128), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('source_quote', sa.Text(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('trigger_reason', sa.Enum('low_confidence', 'rule_llm_disagreement', 'validation_retry', 'citation_unverified', 'vlm_sourced', 'high_value_threshold', 'manual', name='ck_reviewtrigger', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('status', sa.Enum('not_required', 'pending', 'approved', 'rejected', 'corrected', name='ck_reviewstatus', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('reviewer_id', sa.String(length=255), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'not_required') OR (reviewer_id IS NOT NULL AND reviewed_at IS NOT NULL)", name=op.f('ck_human_reviews_resolved_review_has_reviewer')),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name=op.f('ck_human_reviews_confidence_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_human_reviews'))
    )
    op.create_index(op.f('ix_human_reviews_entity_id'), 'human_reviews', ['entity_id'], unique=False)
    op.create_index(op.f('ix_human_reviews_entity_type'), 'human_reviews', ['entity_type'], unique=False)
    op.create_index(op.f('ix_human_reviews_status'), 'human_reviews', ['status'], unique=False)
    op.create_index('ix_human_reviews_status_trigger_reason', 'human_reviews', ['status', 'trigger_reason'], unique=False)
    op.create_index(op.f('ix_human_reviews_trigger_reason'), 'human_reviews', ['trigger_reason'], unique=False)
    op.create_table('instruments',
    sa.Column('issuer_name', sa.String(length=512), nullable=False),
    sa.Column('instrument_name', sa.String(length=512), nullable=False),
    sa.Column('instrument_type', sa.Enum('sukuk', 'conventional_bond', 'mtn', 'perpetual', 'unknown', name='ck_instrumenttype', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('ticker', sa.String(length=64), nullable=True),
    sa.Column('sukuk_structure', sa.Enum('ijarah', 'wakalah', 'musharakah', 'mudharabah', 'murabahah', 'istisna', 'hybrid', 'unknown', name='ck_sukukstructuretype', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('issue_size', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('current_rating', sa.String(length=16), nullable=True),
    sa.Column('current_rating_rank', sa.Integer(), nullable=True),
    sa.Column('rating_agency', sa.Enum('MARC', 'RAM', 'SP', 'MOODYS', 'FITCH', 'unknown', name='ck_ratingagency', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('review_status', sa.Enum('not_required', 'pending', 'approved', 'rejected', 'corrected', name='ck_reviewstatus', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(currency) = 3', name=op.f('ck_instruments_currency_is_iso4217')),
    sa.CheckConstraint('current_rating_rank IS NULL OR current_rating_rank >= 0', name=op.f('ck_instruments_rating_rank_non_negative')),
    sa.CheckConstraint('issue_size IS NULL OR issue_size >= 0', name=op.f('ck_instruments_issue_size_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instruments')),
    sa.UniqueConstraint('isin', name=op.f('uq_instruments_isin'))
    )
    op.create_index(op.f('ix_instruments_current_rating_rank'), 'instruments', ['current_rating_rank'], unique=False)
    op.create_index(op.f('ix_instruments_issuer_name'), 'instruments', ['issuer_name'], unique=False)
    op.create_index(op.f('ix_instruments_maturity_date'), 'instruments', ['maturity_date'], unique=False)
    op.create_index(op.f('ix_instruments_review_status'), 'instruments', ['review_status'], unique=False)
    op.create_table('llm_cache',
    sa.Column('cache_key', sa.String(length=128), nullable=False),
    sa.Column('prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('model_id', sa.String(length=128), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('response_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('hit_count >= 0', name=op.f('ck_llm_cache_hit_count_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_cache')),
    sa.UniqueConstraint('cache_key', name=op.f('uq_llm_cache_cache_key'))
    )
    op.create_index(op.f('ix_llm_cache_prompt_hash'), 'llm_cache', ['prompt_hash'], unique=False)
    op.create_table('portfolios',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('mandate_type', sa.String(length=128), nullable=True),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(base_currency) = 3', name=op.f('ck_portfolios_base_currency_is_iso4217')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolios')),
    sa.UniqueConstraint('name', name=op.f('uq_portfolios_name'))
    )
    op.create_table('query_logs',
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('intent', sa.Enum('document_search', 'covenant_lookup', 'instrument_lookup', 'portfolio_query', 'covenant_breach_check', 'unsupported', name='ck_queryintent', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('retrieved_chunk_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tools_called', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sql_generated', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('citations_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('refused', sa.Boolean(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('NOT refused OR confidence IS NULL OR confidence = 0', name=op.f('ck_query_logs_refusal_has_no_confidence')),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name=op.f('ck_query_logs_confidence_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_query_logs'))
    )
    op.create_index(op.f('ix_query_logs_intent'), 'query_logs', ['intent'], unique=False)
    op.create_index(op.f('ix_query_logs_request_id'), 'query_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_query_logs_user_id'), 'query_logs', ['user_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('section_title', sa.String(length=512), nullable=True),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('chunk_type', sa.Enum('paragraph', 'table', 'heading', 'list', 'footnote', 'unknown', name='ck_chunktype', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('language', sa.Enum('en', 'ms', 'mixed', 'unknown', name='ck_language', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('fts_config', sa.String(length=32), nullable=False),
    sa.Column('fts', postgresql.TSVECTOR(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('embedding_model', sa.String(length=128), nullable=True),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("fts_config IN ('english', 'simple')", name=op.f('ck_document_chunks_fts_config_supported')),
    sa.CheckConstraint('char_end >= char_start', name=op.f('ck_document_chunks_char_span_ordered')),
    sa.CheckConstraint('char_start >= 0', name=op.f('ck_document_chunks_char_start_non_negative')),
    sa.CheckConstraint('page_number >= 1', name=op.f('ck_document_chunks_page_number_positive')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_chunks_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_chunks')),
    sa.UniqueConstraint('document_id', 'hash', name='uq_document_chunks_document_id_hash')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index('ix_document_chunks_document_id_page_number', 'document_chunks', ['document_id', 'page_number'], unique=False)
    op.create_index('ix_document_chunks_embedding_hnsw', 'document_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_document_chunks_fts', 'document_chunks', ['fts'], unique=False, postgresql_using='gin')
    op.create_table('document_pages',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('image_area_ratio', sa.Float(), nullable=False),
    sa.Column('has_text_layer', sa.Boolean(), nullable=False),
    sa.Column('garbled_unicode_ratio', sa.Float(), nullable=False),
    sa.Column('parse_method', sa.Enum('pymupdf', 'pdfplumber', 'vlm', 'none', name='ck_parsemethod', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('vlm_used', sa.Boolean(), nullable=False),
    sa.Column('vlm_reason', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('NOT vlm_used OR vlm_reason IS NOT NULL', name=op.f('ck_document_pages_vlm_use_requires_reason')),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_document_pages_confidence_range')),
    sa.CheckConstraint('page_number >= 1', name=op.f('ck_document_pages_page_number_positive')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_pages_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_pages')),
    sa.UniqueConstraint('document_id', 'page_number', name='uq_document_pages_document_id_page')
    )
    op.create_index(op.f('ix_document_pages_document_id'), 'document_pages', ['document_id'], unique=False)
    op.create_table('extraction_jobs',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('document_sha256', sa.String(length=64), nullable=False),
    sa.Column('job_type', sa.Enum('parse', 'chunk', 'embed', 'classify', 'extract_covenant', 'extract_sukuk_structure', 'extract_call_schedule', 'extract_rating_trigger', 'validate', name='ck_jobtype', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', 'budget_exceeded', 'cancelled', name='ck_jobstatus', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('model_id', sa.String(length=128), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('extractor_version', sa.String(length=64), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('estimated_cost_usd >= 0', name=op.f('ck_extraction_jobs_cost_non_negative')),
    sa.CheckConstraint('prompt_tokens >= 0 AND completion_tokens >= 0', name=op.f('ck_extraction_jobs_tokens_non_negative')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_extraction_jobs_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extraction_jobs')),
    sa.UniqueConstraint('document_sha256', 'job_type', 'prompt_version', 'model_id', 'extractor_version', name='uq_extraction_jobs_identity')
    )
    op.create_index(op.f('ix_extraction_jobs_document_id'), 'extraction_jobs', ['document_id'], unique=False)
    op.create_index(op.f('ix_extraction_jobs_job_type'), 'extraction_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_extraction_jobs_status'), 'extraction_jobs', ['status'], unique=False)
    op.create_index('ix_extraction_jobs_status_job_type', 'extraction_jobs', ['status', 'job_type'], unique=False)
    op.create_table('portfolio_holdings',
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('market_value', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('nav_weight', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('market_value IS NULL OR market_value >= 0', name=op.f('ck_portfolio_holdings_market_value_non_negative')),
    sa.CheckConstraint('nav_weight IS NULL OR (nav_weight >= 0 AND nav_weight <= 1)', name=op.f('ck_portfolio_holdings_nav_weight_is_fraction')),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_portfolio_holdings_instrument_id_instruments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_portfolio_holdings_portfolio_id_portfolios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolio_holdings')),
    sa.UniqueConstraint('portfolio_id', 'instrument_id', 'as_of_date', name='uq_portfolio_holdings_portfolio_id_instrument_id_as_of_date')
    )
    op.create_index(op.f('ix_portfolio_holdings_as_of_date'), 'portfolio_holdings', ['as_of_date'], unique=False)
    op.create_index('ix_portfolio_holdings_as_of_date_portfolio_id', 'portfolio_holdings', ['as_of_date', 'portfolio_id'], unique=False)
    op.create_index(op.f('ix_portfolio_holdings_instrument_id'), 'portfolio_holdings', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_portfolio_holdings_portfolio_id'), 'portfolio_holdings', ['portfolio_id'], unique=False)
    op.create_table('sukuk_structures',
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('structure_type', sa.Enum('ijarah', 'wakalah', 'musharakah', 'mudharabah', 'murabahah', 'istisna', 'hybrid', 'unknown', name='ck_sukukstructuretype', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('spv_name', sa.String(length=512), nullable=True),
    sa.Column('originator', sa.String(length=512), nullable=True),
    sa.Column('underlying_asset', sa.Text(), nullable=True),
    sa.Column('profit_rate', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('profit_payment_frequency', sa.String(length=64), nullable=True),
    sa.Column('purchase_undertaking', sa.Boolean(), nullable=True),
    sa.Column('dissolution_events_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('shariah_compliance_events_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('review_status', sa.Enum('not_required', 'pending', 'approved', 'rejected', 'corrected', name='ck_reviewstatus', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name=op.f('ck_sukuk_structures_confidence_range')),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_sukuk_structures_instrument_id_instruments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sukuk_structures'))
    )
    op.create_index(op.f('ix_sukuk_structures_instrument_id'), 'sukuk_structures', ['instrument_id'], unique=True)
    op.create_index(op.f('ix_sukuk_structures_review_status'), 'sukuk_structures', ['review_status'], unique=False)
    op.create_table('clauses',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=True),
    sa.Column('source_chunk_id', sa.UUID(), nullable=True),
    sa.Column('clause_type', sa.Enum('negative_pledge', 'cross_default', 'change_of_control', 'financial_covenant', 'rating_trigger', 'call_option', 'put_option', 'profit_step_up', 'dissolution_event', 'purchase_undertaking', 'shariah_compliance', 'event_of_default', 'covenant_other', name='ck_clausetype', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('clause_text', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('section_title', sa.String(length=512), nullable=True),
    sa.Column('source_quote', sa.Text(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('citation_verified', sa.Boolean(), nullable=False),
    sa.Column('citation_match_score', sa.Float(), nullable=True),
    sa.Column('normalized_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('method', sa.Enum('rule', 'llm', 'vlm', 'human', name='ck_extractionmethod', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('extraction_status', sa.Enum('pending', 'extracted', 'validation_failed', 'citation_failed', 'budget_exceeded', name='ck_extractionstatus', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('review_status', sa.Enum('not_required', 'pending', 'approved', 'rejected', 'corrected', name='ck_reviewstatus', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('NOT citation_verified OR citation_match_score IS NOT NULL', name=op.f('ck_clauses_verified_citation_has_score')),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name=op.f('ck_clauses_confidence_range')),
    sa.CheckConstraint('length(source_quote) > 0', name=op.f('ck_clauses_source_quote_not_empty')),
    sa.CheckConstraint('page_number >= 1', name=op.f('ck_clauses_page_number_positive')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_clauses_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_clauses_instrument_id_instruments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['document_chunks.id'], name=op.f('fk_clauses_source_chunk_id_document_chunks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clauses'))
    )
    op.create_index(op.f('ix_clauses_clause_type'), 'clauses', ['clause_type'], unique=False)
    op.create_index(op.f('ix_clauses_document_id'), 'clauses', ['document_id'], unique=False)
    op.create_index('ix_clauses_document_id_clause_type', 'clauses', ['document_id', 'clause_type'], unique=False)
    op.create_index(op.f('ix_clauses_extraction_status'), 'clauses', ['extraction_status'], unique=False)
    op.create_index(op.f('ix_clauses_instrument_id'), 'clauses', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_clauses_review_status'), 'clauses', ['review_status'], unique=False)
    op.create_index(op.f('ix_clauses_source_chunk_id'), 'clauses', ['source_chunk_id'], unique=False)
    op.create_table('llm_calls',
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('stage', sa.Enum('classify', 'section_detect', 'vlm_ocr', 'embed', 'extract', 'validate', 'synthesize', 'judge', name='ck_llmstage', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model_id', sa.String(length=128), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_write_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cache_hit = false OR estimated_cost_usd = 0', name=op.f('ck_llm_calls_cache_hit_is_free')),
    sa.CheckConstraint('estimated_cost_usd >= 0', name=op.f('ck_llm_calls_cost_non_negative')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_llm_calls_document_id_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['extraction_jobs.id'], name=op.f('fk_llm_calls_job_id_extraction_jobs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_calls'))
    )
    op.create_index(op.f('ix_llm_calls_document_id'), 'llm_calls', ['document_id'], unique=False)
    op.create_index('ix_llm_calls_document_id_stage', 'llm_calls', ['document_id', 'stage'], unique=False)
    op.create_index(op.f('ix_llm_calls_job_id'), 'llm_calls', ['job_id'], unique=False)
    op.create_index(op.f('ix_llm_calls_stage'), 'llm_calls', ['stage'], unique=False)
    op.create_table('call_schedules',
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('source_clause_id', sa.UUID(), nullable=True),
    sa.Column('call_date', sa.Date(), nullable=False),
    sa.Column('call_price', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('call_type', sa.Enum('optional', 'mandatory', 'make_whole', 'clean_up', 'tax', 'regulatory', name='ck_calltype', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('conditions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('method', sa.Enum('rule', 'llm', 'vlm', 'human', name='ck_extractionmethod', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('review_status', sa.Enum('not_required', 'pending', 'approved', 'rejected', 'corrected', name='ck_reviewstatus', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('call_price IS NULL OR call_price > 0', name=op.f('ck_call_schedules_call_price_positive')),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name=op.f('ck_call_schedules_confidence_range')),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_call_schedules_instrument_id_instruments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_clause_id'], ['clauses.id'], name=op.f('fk_call_schedules_source_clause_id_clauses'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_call_schedules'))
    )
    op.create_index(op.f('ix_call_schedules_call_date'), 'call_schedules', ['call_date'], unique=False)
    op.create_index(op.f('ix_call_schedules_instrument_id'), 'call_schedules', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_call_schedules_review_status'), 'call_schedules', ['review_status'], unique=False)
    op.create_index(op.f('ix_call_schedules_source_clause_id'), 'call_schedules', ['source_clause_id'], unique=False)
    op.create_table('covenants',
    sa.Column('clause_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=True),
    sa.Column('covenant_type', sa.Enum('negative_pledge', 'cross_default', 'change_of_control', 'gearing_ratio', 'interest_cover', 'finance_service_cover', 'minimum_net_worth', 'rating_trigger', 'disposal_restriction', 'distribution_restriction', 'shariah_non_compliance', 'other', name='ck_covenanttype', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('conditions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('thresholds_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('threshold_amount', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('threshold_currency', sa.String(length=3), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('trigger_event', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('informational', 'low', 'medium', 'high', 'critical', name='ck_severity', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('method', sa.Enum('rule', 'llm', 'vlm', 'human', name='ck_extractionmethod', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('review_status', sa.Enum('not_required', 'pending', 'approved', 'rejected', 'corrected', name='ck_reviewstatus', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name=op.f('ck_covenants_confidence_range')),
    sa.CheckConstraint('threshold_amount IS NULL OR threshold_currency IS NOT NULL', name=op.f('ck_covenants_threshold_amount_requires_currency')),
    sa.ForeignKeyConstraint(['clause_id'], ['clauses.id'], name=op.f('fk_covenants_clause_id_clauses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_covenants_instrument_id_instruments'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_covenants'))
    )
    op.create_index(op.f('ix_covenants_clause_id'), 'covenants', ['clause_id'], unique=False)
    op.create_index(op.f('ix_covenants_covenant_type'), 'covenants', ['covenant_type'], unique=False)
    op.create_index(op.f('ix_covenants_instrument_id'), 'covenants', ['instrument_id'], unique=False)
    op.create_index('ix_covenants_instrument_id_covenant_type', 'covenants', ['instrument_id', 'covenant_type'], unique=False)
    op.create_index(op.f('ix_covenants_review_status'), 'covenants', ['review_status'], unique=False)
    op.create_index(op.f('ix_covenants_threshold_amount'), 'covenants', ['threshold_amount'], unique=False)
    op.create_table('rating_triggers',
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('source_clause_id', sa.UUID(), nullable=True),
    sa.Column('rating_agency', sa.Enum('MARC', 'RAM', 'SP', 'MOODYS', 'FITCH', 'unknown', name='ck_ratingagency', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('trigger_rating', sa.String(length=16), nullable=False),
    sa.Column('trigger_rank', sa.Integer(), nullable=False),
    sa.Column('trigger_direction', sa.Enum('downgrade_below', 'upgrade_above', 'withdrawal', 'any_change', name='ck_triggerdirection', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('consequence', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('informational', 'low', 'medium', 'high', 'critical', name='ck_severity', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('method', sa.Enum('rule', 'llm', 'vlm', 'human', name='ck_extractionmethod', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('review_status', sa.Enum('not_required', 'pending', 'approved', 'rejected', 'corrected', name='ck_reviewstatus', native_enum=False, create_constraint=True, length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name=op.f('ck_rating_triggers_confidence_range')),
    sa.CheckConstraint('length(trigger_rating) > 0', name=op.f('ck_rating_triggers_trigger_rating_not_empty')),
    sa.CheckConstraint('trigger_rank >= 0', name=op.f('ck_rating_triggers_trigger_rank_non_negative')),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_rating_triggers_instrument_id_instruments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_clause_id'], ['clauses.id'], name=op.f('fk_rating_triggers_source_clause_id_clauses'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rating_triggers'))
    )
    op.create_index(op.f('ix_rating_triggers_instrument_id'), 'rating_triggers', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_rating_triggers_review_status'), 'rating_triggers', ['review_status'], unique=False)
    op.create_index(op.f('ix_rating_triggers_source_clause_id'), 'rating_triggers', ['source_clause_id'], unique=False)
    op.create_index(op.f('ix_rating_triggers_trigger_rank'), 'rating_triggers', ['trigger_rank'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rating_triggers_trigger_rank'), table_name='rating_triggers')
    op.drop_index(op.f('ix_rating_triggers_source_clause_id'), table_name='rating_triggers')
    op.drop_index(op.f('ix_rating_triggers_review_status'), table_name='rating_triggers')
    op.drop_index(op.f('ix_rating_triggers_instrument_id'), table_name='rating_triggers')
    op.drop_table('rating_triggers')
    op.drop_index(op.f('ix_covenants_threshold_amount'), table_name='covenants')
    op.drop_index(op.f('ix_covenants_review_status'), table_name='covenants')
    op.drop_index('ix_covenants_instrument_id_covenant_type', table_name='covenants')
    op.drop_index(op.f('ix_covenants_instrument_id'), table_name='covenants')
    op.drop_index(op.f('ix_covenants_covenant_type'), table_name='covenants')
    op.drop_index(op.f('ix_covenants_clause_id'), table_name='covenants')
    op.drop_table('covenants')
    op.drop_index(op.f('ix_call_schedules_source_clause_id'), table_name='call_schedules')
    op.drop_index(op.f('ix_call_schedules_review_status'), table_name='call_schedules')
    op.drop_index(op.f('ix_call_schedules_instrument_id'), table_name='call_schedules')
    op.drop_index(op.f('ix_call_schedules_call_date'), table_name='call_schedules')
    op.drop_table('call_schedules')
    op.drop_index(op.f('ix_llm_calls_stage'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_job_id'), table_name='llm_calls')
    op.drop_index('ix_llm_calls_document_id_stage', table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_document_id'), table_name='llm_calls')
    op.drop_table('llm_calls')
    op.drop_index(op.f('ix_clauses_source_chunk_id'), table_name='clauses')
    op.drop_index(op.f('ix_clauses_review_status'), table_name='clauses')
    op.drop_index(op.f('ix_clauses_instrument_id'), table_name='clauses')
    op.drop_index(op.f('ix_clauses_extraction_status'), table_name='clauses')
    op.drop_index('ix_clauses_document_id_clause_type', table_name='clauses')
    op.drop_index(op.f('ix_clauses_document_id'), table_name='clauses')
    op.drop_index(op.f('ix_clauses_clause_type'), table_name='clauses')
    op.drop_table('clauses')
    op.drop_index(op.f('ix_sukuk_structures_review_status'), table_name='sukuk_structures')
    op.drop_index(op.f('ix_sukuk_structures_instrument_id'), table_name='sukuk_structures')
    op.drop_table('sukuk_structures')
    op.drop_index(op.f('ix_portfolio_holdings_portfolio_id'), table_name='portfolio_holdings')
    op.drop_index(op.f('ix_portfolio_holdings_instrument_id'), table_name='portfolio_holdings')
    op.drop_index('ix_portfolio_holdings_as_of_date_portfolio_id', table_name='portfolio_holdings')
    op.drop_index(op.f('ix_portfolio_holdings_as_of_date'), table_name='portfolio_holdings')
    op.drop_table('portfolio_holdings')
    op.drop_index('ix_extraction_jobs_status_job_type', table_name='extraction_jobs')
    op.drop_index(op.f('ix_extraction_jobs_status'), table_name='extraction_jobs')
    op.drop_index(op.f('ix_extraction_jobs_job_type'), table_name='extraction_jobs')
    op.drop_index(op.f('ix_extraction_jobs_document_id'), table_name='extraction_jobs')
    op.drop_table('extraction_jobs')
    op.drop_index(op.f('ix_document_pages_document_id'), table_name='document_pages')
    op.drop_table('document_pages')
    op.drop_index('ix_document_chunks_fts', table_name='document_chunks', postgresql_using='gin')
    op.drop_index('ix_document_chunks_embedding_hnsw', table_name='document_chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_document_chunks_document_id_page_number', table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_query_logs_user_id'), table_name='query_logs')
    op.drop_index(op.f('ix_query_logs_request_id'), table_name='query_logs')
    op.drop_index(op.f('ix_query_logs_intent'), table_name='query_logs')
    op.drop_table('query_logs')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_llm_cache_prompt_hash'), table_name='llm_cache')
    op.drop_table('llm_cache')
    op.drop_index(op.f('ix_instruments_review_status'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_maturity_date'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_issuer_name'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_current_rating_rank'), table_name='instruments')
    op.drop_table('instruments')
    op.drop_index(op.f('ix_human_reviews_trigger_reason'), table_name='human_reviews')
    op.drop_index('ix_human_reviews_status_trigger_reason', table_name='human_reviews')
    op.drop_index(op.f('ix_human_reviews_status'), table_name='human_reviews')
    op.drop_index(op.f('ix_human_reviews_entity_type'), table_name='human_reviews')
    op.drop_index(op.f('ix_human_reviews_entity_id'), table_name='human_reviews')
    op.drop_table('human_reviews')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity_type_entity_id', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
